version: "3.7"
services:
  nethermind:
    image: nethermind/nethermind:latest
    container_name: nethermind
    restart: always
    env_file: .env
    stop_grace_period: 2m
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${WS_PORT}:${WS_PORT}
      - ${P2P_PORT}:${P2P_PORT}/tcp
      - ${P2P_PORT}:${P2P_PORT}/udp
    command:
      - --datadir
      - /var/lib/nethermind
      - --Init.WebSocketsEnabled
      - "true"
      - --Network.DiscoveryPort
      - "${P2P_PORT}"
      - --Network.P2PPort
      - "${P2P_PORT}"
      - --JsonRpc.Enabled
      - "true"
      - --JsonRpc.EnabledModules
      - "Web3,Eth,Subscribe,Net,Parity"
      - --JsonRpc.Host
      - "0.0.0.0"
      - --JsonRpc.Port
      - "${HTTP_PORT}"
      - --JsonRpc.WebSocketsPort
      - "${WS_PORT}"
      - --Sync.FastSync
      - "true"
      - --config
      - xdai
      - --Pruning.Enabled
      - "true"
      - --Pruning.CacheMb
      - "4096"
      - --TxPool.Size
      - "4096"
      - --Sync.AncientBodiesBarrier
      - "1"
      - --Sync.AncientReceiptsBarrier
      - "1"
    volumes:
      - ./nethermind-data:/var/lib/nethermind